###
POST http://localhost:8001/member/passenger/save
Content-Type: application/json

{
  "memberId": "12345678001",
  "name": "test",
  "idCard": "123321",
  "type": "1"
}

###
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
#token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3MzkwMDYzNjgsIm1vYmlsZSI6IjEyMzQ1Njc4MDAxIiwiaWQiOjE4ODQ5MjEwNDY4MzEzMTY5OTIsImV4cCI6MTczOTA5Mjc2OCwiaWF0IjoxNzM5MDA2MzY4fQ.JK8CBv6L-hkFfIYYcYxi70Rx5oxc1LzIHi3bRs9ZyyE
token: {{token}}

{
  "name": "test",
  "idCard": "123321",
  "type": "1"
}

###
GET http://localhost:8000/member/passenger/query-list
Accept: application/json
token: {{token}}

###
GET http://localhost:8000/member/passenger/query-list?page=1&size=200
Accept: application/json
token: {{token}}

###
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
#token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3MzkwMDYzNjgsIm1vYmlsZSI6IjEyMzQ1Njc4MDAxIiwiaWQiOjE4ODQ5MjEwNDY4MzEzMTY5OTIsImV4cCI6MTczOTA5Mjc2OCwiaWF0IjoxNzM5MDA2MzY4fQ.JK8CBv6L-hkFfIYYcYxi70Rx5oxc1LzIHi3bRs9ZyyE
token: {{token}}

{
  "id" : 1888165051572523008,
  "memberId" : 1884921046831316992,
  "name": "test1",
  "idCard": "123321",
  "type": "1"
}